# Assignment 1 (Machine Learning)
> This assignment is solved by:-
* Name: Vishal Sehgal
* Group: CO11
* Roll Number: 102003265

In [296]:
import numpy as np

### Question 1

> a

In [297]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [298]:
reverse_arr = arr[::-1]
print(reverse_arr)

[5 4 6 3 2 1]


> b

In [299]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

In [300]:
print(array1.flatten())
print(array1.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


> c

In [301]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])

In [302]:
arr1 == arr2

array([[ True,  True],
       [ True,  True]])

In [303]:
np.greater(arr1, arr2)

array([[False, False],
       [False, False]])

In [304]:
np.greater_equal(arr1, arr2)

array([[ True,  True],
       [ True,  True]])

In [305]:
np.less(arr1,arr2)

array([[False, False],
       [False, False]])

In [306]:
np.less_equal(arr1, arr2)

array([[ True,  True],
       [ True,  True]])

> d

In [307]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [308]:
# i)
print(np.bincount(x).argmax(), np.where(x == np.bincount(x).argmax()))
# ii)
data = np.bincount(y)
freq_eles = np.where(np.bincount(y) == max(data))[0]
print(freq_eles)
for i in freq_eles:
    print(i, end=": ")
    for j in range(len(y)):
        if(i==y[j]):
            print(j, end=" ")
    print()

1 (array([0, 5, 7, 8, 9]),)
[1 3]
1: 0 1 2 
3: 4 8 9 


> e

In [309]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [310]:
# i)
print(f"Sum of matrix: {np.sum(gfg)}")
# ii)
print(f"Sum of matrix row-wise: {np.sum(gfg, axis=0)}")
# iii)
print(f"Sum of matrix column-wise: {np.sum(gfg, axis=1)}")

Sum of matrix: 45
Sum of matrix row-wise: [[20  9 16]]
Sum of matrix column-wise: [[14]
 [16]
 [15]]


> f

In [311]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

In [312]:
# i)
print(np.trace(n_array))

176


In [313]:
eval, evec = np.linalg.eig(n_array)
# ii)
print(eval)
# iii)
print(evec)

[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [314]:
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [315]:
np.linalg.det(n_array)

137180.0000000001

> g

In [316]:
# i)
p = np.matrix([[1, 2], [2, 3]])
q = np.matrix([[4, 5], [6, 7]])
print(np.dot(p, q))
np.cov(np.concatenate((p,q), axis=1))

[[16 19]
 [26 31]]


array([[3.33333333, 4.33333333],
       [4.33333333, 5.66666667]])

In [317]:
# ii)
p = np.matrix([[1, 2], [2, 3], [4, 5]])
q = np.matrix([[4, 5, 1], [6, 7, 2]])
print(np.dot(p, q))
np.cov(np.concatenate((p.flatten(), q.flatten()), axis= 0))

[[16 19  5]
 [26 31  8]
 [46 55 14]]


array([[2.16666667, 0.23333333],
       [0.23333333, 5.36666667]])

> h

In [318]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


### Question 2

#### a)

In [319]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

> i.

In [320]:
print(np.abs(array))

[[1 2 3]
 [4 5 6]]


> ii.

In [321]:
array_flatt = array.flatten()
print(f"25% percentile: {np.percentile(array_flatt, 25)}")
print(f"50% percentile: {np.percentile(array_flatt, 50)}")
print(f"75% percentile: {np.percentile(array_flatt, 75)}")

25% percentile: -3.5
50% percentile: -0.5
75% percentile: 2.5


In [322]:
print(f"25% percentile: {np.percentile(array, 25, axis=0)}")
print(f"50% percentile: {np.percentile(array, 50, axis=0)}")
print(f"75% percentile: {np.percentile(array, 75, axis=0)}")

25% percentile: [-2.75 -0.25 -3.75]
50% percentile: [-1.5  1.5 -1.5]
75% percentile: [-0.25  3.25  0.75]


In [323]:
print(f"25% percentile: {np.percentile(array, 25, axis=1)}")
print(f"50% percentile: {np.percentile(array, 50, axis=1)}")
print(f"75% percentile: {np.percentile(array, 75, axis=1)}")

25% percentile: [-0.5 -5. ]
50% percentile: [ 1. -4.]
75% percentile: [2.  0.5]


> iii.

In [324]:
print(np.mean(array_flatt))
print(np.median(array_flatt))
print(np.std(array_flatt))

-0.5
-0.5
3.8622100754188224


In [325]:
print(np.mean(array, axis=0))
print(np.median(array, axis=0))
print(np.std(array, axis=0))

[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]


In [326]:
print(np.mean(array, axis=1))
print(np.median(array, axis=1))
print(np.std(array, axis=1))

[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


#### b)

In [327]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [328]:
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


### Question 3

#### a)

In [329]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

> i

In [330]:
print(f"Sorted Array: {np.sort(array)}")

Sorted Array: [ 10  16  16  52  54  62 453]


> ii

In [331]:
print(np.argsort(array))

[0 3 4 1 5 2 6]


> iii

In [332]:
array[np.argpartition(array, 4)[:4]]

array([16, 10, 16, 52])

> iv

In [333]:
array[np.argpartition(array, 4)[-5:]]

array([ 16,  52,  54,  62, 453])

#### b)

In [334]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

> i

In [335]:
array[[not (i%1) for i in array]]

array([1., 2., 3., 2.])

> ii

In [336]:
print(array[array!=array.astype(int)])

[1.2 2.2]


### Question 4

> a

In [337]:
# Install Pillow first using: pip install Pillow OR conda install Pillow

In [338]:
from PIL import Image
img = Image.open('./Vishal_Sehgal.jpeg')

In [339]:
def img_to_array(path):
    img = Image.open(path)
    numpyData = np.asarray(img)
    img_reshaped = numpyData.reshape(numpyData.shape[0], -1)
    np.savetxt('data.out', img_reshaped, delimiter=',')
    return numpyData

In [340]:
data = img_to_array('./Vishal_Sehgal.jpeg')

> b

In [341]:
numpydata = np.loadtxt('data.out', dtype='uint8', delimiter=',')

In [342]:
data.shape
array3D = numpydata.reshape(numpydata.shape[0], numpydata.shape[1] // data.shape[2], data.shape[2])

In [343]:
im = Image.fromarray(array3D)
im.show()