# Assignment 5 (Machine Learning)
> This assignment is solved by:-
* Name: Vishal Sehgal
* Group: CO11
* Roll Number: 102003265

### Question 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
X, y = load_iris(return_X_y=True)

In [4]:
X.shape

(150, 4)

In [5]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = np.insert(X_scaled, 0, values=1, axis=1)

In [25]:
len(y[y == 0]), len(y[y == 1]), len(y[y == 2])

(50, 50, 50)

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [45]:
zero_list = []
one_list = []
for i in range(len(y_train)):
    if(y_train[i]==0):
        zero_list.append(i)
    elif(y_train[i]==1):
        one_list.append(i)
print(zero_list)
print(one_list)

[0, 1, 3, 4, 7, 8, 9, 13, 14, 23, 26, 27, 28, 31, 32, 33, 35, 38, 41, 48, 51, 52, 55, 57, 58, 66, 67, 70, 71, 72, 75, 78, 84, 91, 94, 98, 102, 104, 114, 117]
[2, 6, 11, 12, 15, 18, 20, 22, 25, 29, 34, 36, 39, 44, 45, 47, 49, 53, 54, 59, 60, 62, 65, 73, 79, 80, 82, 86, 88, 89, 90, 92, 93, 95, 99, 105, 108, 110, 111, 115, 118]


In [43]:
len(X_train)

120

In [48]:
y_train_zero = []
y_train_one = []
for i in range(len(X_train)):
    if(zero_list.count(i)):
        y_train_zero.append(0)
    else:
        y_train_zero.append(1)
    if(one_list.count(i)):
        y_train_one.append(1)
    else:
        y_train_one.append(0)
print(y_train_zero)
print(y_train_one)

[0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1]
[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0]


In [51]:
n = 1000
alpha = 0.01
m, k = X_train.shape
beta_zero = np.zeros(k)
for i in range(n):
    cost_gradient = np.zeros(k)
    z = X_train.dot(beta_zero)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - y_train_zero
    for j in range(k):
        cost_gradient[j] = np.sum(difference.dot(X_train[:, j]))
    for j in range(k):
        beta_zero[j] = beta_zero[j] - (alpha/m)*cost_gradient[j]
print(beta_zero)

[ 0.81536848  0.6380633  -0.91583982  1.04481674  0.97361716]


In [52]:
n = 1000
alpha = 0.01
m, k = X_train.shape
beta_one = np.zeros(k)
for i in range(n):
    cost_gradient = np.zeros(k)
    z = X_train.dot(beta_one)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - y_train_one
    for j in range(k):
        cost_gradient[j] = np.sum(difference.dot(X_train[:, j]))
    for j in range(k):
        beta_one[j] = beta_one[j] - (alpha/m)*cost_gradient[j]
print(beta_one)

[-0.66183225  0.05768169 -0.90919961  0.17741897 -0.09469135]


In [53]:
y_pred_zero = 1/(1+np.exp(-(X_test.dot(beta_zero))))
y_pred_one = 1/(1+np.exp(-(X_test.dot(beta_one))))

y_label_zero = np.zeros(len(y_pred_zero))
y_label_one = np.zeros(len(y_pred_one))

for i in range(len(y_pred_zero)):
    if(y_pred_zero[i]>=0.5):
        y_label_zero[i] = 1
    if(y_pred_one[i]>=0.5):
        y_label_one[i] = 1
print(y_label_one)
print(y_label_zero)

[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0.]
[1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1.
 1. 1. 1. 1. 0. 0.]


In [54]:
y_label = np.zeros(len(y_pred_zero))

for i in range(len(y_label)):
    if(y_label_zero[i]==1):
        if(y_label_one[i]==1):
            y_label[i] = 1
        else:
            y_label[i] = 2

print(y_label)

[2. 0. 1. 2. 1. 0. 2. 2. 1. 1. 2. 0. 0. 0. 0. 2. 2. 1. 2. 2. 0. 2. 0. 2.
 2. 2. 1. 2. 0. 0.]


In [55]:
TP=0
TN=0
FP=0
FN=0 
y_test=np.array(y_test).reshape(-1,1) 
for i in range(len(y_label)):
    if(y_test[i]==1 and y_label[i]==1): 
        TP=TP+1
    if(y_test[i]==1 and y_label[i]==0): 
        FN=FN+1
    if(y_test[i]==0 and y_label[i]==1): 
        FP=FP+1
    if(y_test[i]==0 and y_label[i]==0): 
        TN=TN+1
print(TP,TN,FP,FN)
accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy*100)

4 10 0 0
100.0


### Question 2

In [61]:
df = pd.read_csv('exam6.txt', names=['test1', 'test2', 'status'])

In [62]:
df.head()

test1    test2  status
0  0.051267  0.69956       1
1 -0.092742  0.68494       1
2 -0.213710  0.69225       1
3 -0.375000  0.50219       1
4 -0.513250  0.46564       1

In [63]:
X = df.drop('status', axis=1)
y = df['status']
X = np.array(X)
y = np.array(y)

In [71]:
from sklearn.preprocessing import PolynomialFeatures
obj = PolynomialFeatures(degree=6)
X_transformed = obj.fit_transform(X)

In [72]:
X_transformed.shape

(118, 28)

In [73]:
X_transformed

array([[ 1.00000000e+00,  5.12670000e-02,  6.99560000e-01, ...,
         6.29470940e-04,  8.58939846e-03,  1.17205992e-01],
       [ 1.00000000e+00, -9.27420000e-02,  6.84940000e-01, ...,
         1.89305413e-03, -1.39810280e-02,  1.03255971e-01],
       [ 1.00000000e+00, -2.13710000e-01,  6.92250000e-01, ...,
         1.04882142e-02, -3.39734512e-02,  1.10046893e-01],
       ...,
       [ 1.00000000e+00, -4.84450000e-01,  9.99270000e-01, ...,
         2.34007252e-01, -4.82684337e-01,  9.95627986e-01],
       [ 1.00000000e+00, -6.33640000e-03,  9.99270000e-01, ...,
         4.00328554e-05, -6.31330588e-03,  9.95627986e-01],
       [ 1.00000000e+00,  6.32650000e-01, -3.06120000e-02, ...,
         3.51474517e-07, -1.70067777e-08,  8.22905998e-10]])

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.2, random_state=42)

> i.

In [79]:
n = 1000
alpha = 10
m, k = X_train.shape
beta = np.zeros(k)
for i in range(n):
    cost_gradient = np.zeros(k)
    z = X_train.dot(beta)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - y_train
    for j in range(k):
        cost_gradient[j] = np.sum(difference.dot(X_train[:, j]))
    for j in range(k):
        beta[j] = beta[j] - (alpha/m)*cost_gradient[j]
print(beta)

[ 3.79171422  0.75931817  5.28450188 -6.08383449 -6.81616066 -6.0703927
  4.54691492  1.07650365  2.27449109 -2.7951547  -3.8358596   4.38592634
 -3.39003485 -3.35779843 -5.96318974 -0.63898705 -3.81042552  8.00544377
 -3.07246874 -5.4449508   2.06724483 -6.08866458  0.70514218 -1.05517887
  3.83127972 -3.85437726 -4.94564416 -0.104631  ]


In [80]:
y_pred = 1/(1+np.exp(-(X_test.dot(beta))))

y_label = np.zeros(len(y_pred))

for i in range(len(y_pred)):
    if(y_pred[i]>=0.5):
        y_label[i] = 1
print(y_label)

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1.]


In [81]:
TP=0
TN=0
FP=0
FN=0 
y_test=np.array(y_test).reshape(-1,1) 
for i in range(len(y_label)):
    if(y_test[i]==1 and y_label[i]==1): 
        TP=TP+1
    if(y_test[i]==1 and y_label[i]==0): 
        FN=FN+1
    if(y_test[i]==0 and y_label[i]==1): 
        FP=FP+1
    if(y_test[i]==0 and y_label[i]==0): 
        TN=TN+1
print(TP,TN,FP,FN)
accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy*100)

11 10 2 1
87.5


> ii.

In [82]:
n = 1000
alpha = 10
lam = 0.2
m, k = X_train.shape
beta = np.zeros(k)
for i in range(n):
    cost_gradient = np.zeros(k)
    z = X_train.dot(beta)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - y_train
    for j in range(k):
        cost_gradient[j] = np.sum(difference.dot(X_train[:, j]))
    for j in range(k):
        beta[j] = beta[j]*(1-((alpha*lam)/m)) - (alpha/m)*cost_gradient[j]
print(beta)

[ 2.65990665  0.96563552  2.66159741 -3.23714945 -2.05234705 -2.76422725
  0.94386227 -0.78277901 -0.91625212 -0.06347479 -2.48546624  0.21368133
 -1.18506288 -0.97381355 -2.07466113 -0.04341013 -0.69980184  0.28805226
 -0.56545382 -1.02657718 -0.43903014 -1.92083309  0.20667662 -0.57238135
  0.13955562 -0.61846073 -0.74428497 -1.2971202 ]


In [83]:
y_pred = 1/(1+np.exp(-(X_test.dot(beta))))

y_label = np.zeros(len(y_pred))

for i in range(len(y_pred)):
    if(y_pred[i]>=0.5):
        y_label[i] = 1
print(y_label)

[1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1.]


In [84]:
TP=0
TN=0
FP=0
FN=0 
y_test=np.array(y_test).reshape(-1,1) 
for i in range(len(y_label)):
    if(y_test[i]==1 and y_label[i]==1): 
        TP=TP+1
    if(y_test[i]==1 and y_label[i]==0): 
        FN=FN+1
    if(y_test[i]==0 and y_label[i]==1): 
        FP=FP+1
    if(y_test[i]==0 and y_label[i]==0): 
        TN=TN+1
print(TP,TN,FP,FN)
accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy*100)

12 9 3 0
87.5
